server:
  port: 8182


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/hbt-prototype-real
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: hbt-payment-service
  h2:
    console:
      enable: true
logging:
  file: C:/Heinsohn/Microservice/microservice.log