server:
  port: 8181


spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: hbt-order-service
  h2:
    console:
      enable: true
logging:
  file: C:/Heinsohn/Microservice/microservice.log