
spring:
  application:
    name: HBT-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hbt-api-test/config-server-app

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5000/eureka
